version: '3'
services:
  mongodb:
    image: "mongo"
    ports:
     - "27017:27017"
    restart: always
  server:
    build: ./robio-server/
    ports:
      - "6200:6200"
    volumes:
      - ./robio-server:/src/app
    depends_on:
      - mongodb
    restart: always
  client:
    build: ./robio-client/
    ports:
      - "3000:3000"
    volumes:
      - ./robio-client:/src/app
    depends_on:
      - server
    restart: always